import Head from "next/head";
import { useState } from "react";
import { useQuery, gql } from "@apollo/client";

const GET_MOVIE = gql`
  query GetMovie($where: MovieWhere) {
    movies(where: $where) {
      title
      crew {
        name
      }
      actors {
        name
      }
    }
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Query />
    </>
  );
}
function Query() {
  const [inputValue, setInputValue] = useState("");
  const [id, setid] = useState(0);
  const { loading, error, data } = useQuery(GET_MOVIE, {
    variables: {
      where: {
        movie_id: id,
      },
    },
  });

  const updateId = (e: any) => {
    setid(Number(inputValue));
    e.preventDefault();
  };
  return (
    <div>
      <form onSubmit={updateId}>
        <input
          type="number"
          name="name"
          value={inputValue}
          onChange={(e) => {
            setInputValue(e.target.value);
          }}
        />
      </form>
      {loading ? (
        <p>Loading...</p>
      ) : (
        <div>
          {data &&
            data.movies.map(({ title, crew, actors }: any) => (
              <div key={title}>
                <h1>{title}</h1> <h2>Cast:</h2>
                <p>{actors.map((c: any) => c.name).join(", ")}</p>
                <h2>Crew:</h2> <p>{crew.map((c: any) => c.name).join(", ")}</p>
              </div>
            ))}
        </div>
      )}
    </div>
  );
}
